#
# target: prereq1, prereq2
#     commands
#
#   target is the file or thing that msut be made.
#
#   prerequisites or dependents are those files that must exist before the
# target can be sucessfully created.
#
#   commands are those shell commands that will create the target from the 
# prerequisites.
#

all : main.c
	gcc main.c -o main
